<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ContagemAveBoia extends \ContagemAveBoia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLance(\DadosAbioticos $lance = NULL)
    {
        $this->__load();
        return parent::setLance($lance);
    }

    public function getLance()
    {
        $this->__load();
        return parent::getLance();
    }

    public function setBoiaRadio($boiaRadio)
    {
        $this->__load();
        return parent::setBoiaRadio($boiaRadio);
    }

    public function getBoiaRadio()
    {
        $this->__load();
        return parent::getBoiaRadio();
    }

    public function setDataHora($dataHora)
    {
        $this->__load();
        return parent::setDataHora($dataHora);
    }

    public function getDataHora()
    {
        $this->__load();
        return parent::getDataHora();
    }

    public function setTemperaturaAgua($temperaturaAgua)
    {
        $this->__load();
        return parent::setTemperaturaAgua($temperaturaAgua);
    }

    public function getTemperaturaAgua()
    {
        $this->__load();
        return parent::getTemperaturaAgua();
    }

    public function setProfundidade($profundidade)
    {
        $this->__load();
        return parent::setProfundidade($profundidade);
    }

    public function getProfundidade()
    {
        $this->__load();
        return parent::getProfundidade();
    }

    public function setPressaoAtmosferica($pressaoAtmosferica)
    {
        $this->__load();
        return parent::setPressaoAtmosferica($pressaoAtmosferica);
    }

    public function getPressaoAtmosferica()
    {
        $this->__load();
        return parent::getPressaoAtmosferica();
    }

    public function setCoordenada($coordenada)
    {
        $this->__load();
        return parent::setCoordenada($coordenada);
    }

    public function getCoordenada()
    {
        $this->__load();
        return parent::getCoordenada();
    }

    public function setCruzeiro(\Cruzeiro $cruzeiro = NULL)
    {
        $this->__load();
        return parent::setCruzeiro($cruzeiro);
    }

    public function getCruzeiro()
    {
        $this->__load();
        return parent::getCruzeiro();
    }

    public function addContagemAveEspecieBoia(\ContagemAveBoiaEspecie $contagemAveBoiaEspecie)
    {
        $this->__load();
        return parent::addContagemAveEspecieBoia($contagemAveBoiaEspecie);
    }

    public function getContagemAveBoiaEspecie()
    {
        $this->__load();
        return parent::getContagemAveBoiaEspecie();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'boiaRadio', 'dataHora', 'temperaturaAgua', 'profundidade', 'pressaoAtmosferica', 'coordenada', 'lance', 'cruzeiro', 'contagemAveBoiaEspecie');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}