<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CadEmbarcacao extends \CadEmbarcacao implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setAutorizacaoPesca($autorizacaoPesca)
    {
        $this->__load();
        return parent::setAutorizacaoPesca($autorizacaoPesca);
    }

    public function getAutorizacaoPesca()
    {
        $this->__load();
        return parent::getAutorizacaoPesca();
    }

    public function setRegMarinha($regMarinha)
    {
        $this->__load();
        return parent::setRegMarinha($regMarinha);
    }

    public function getRegMarinha()
    {
        $this->__load();
        return parent::getRegMarinha();
    }

    public function setRegMpa($regMpa)
    {
        $this->__load();
        return parent::setRegMpa($regMpa);
    }

    public function getRegMpa()
    {
        $this->__load();
        return parent::getRegMpa();
    }

    public function setComprimBarco($comprimBarco)
    {
        $this->__load();
        return parent::setComprimBarco($comprimBarco);
    }

    public function getComprimBarco()
    {
        $this->__load();
        return parent::getComprimBarco();
    }

    public function setArqueacaoBruta($arqueacaoBruta)
    {
        $this->__load();
        return parent::setArqueacaoBruta($arqueacaoBruta);
    }

    public function getArqueacaoBruta()
    {
        $this->__load();
        return parent::getArqueacaoBruta();
    }

    public function setAnoFabricacao($anoFabricacao)
    {
        $this->__load();
        return parent::setAnoFabricacao($anoFabricacao);
    }

    public function getAnoFabricacao()
    {
        $this->__load();
        return parent::getAnoFabricacao();
    }

    public function setMatCasco($matCasco)
    {
        $this->__load();
        return parent::setMatCasco($matCasco);
    }

    public function getMatCasco()
    {
        $this->__load();
        return parent::getMatCasco();
    }

    public function setPropulsao($propulsao)
    {
        $this->__load();
        return parent::setPropulsao($propulsao);
    }

    public function getPropulsao()
    {
        $this->__load();
        return parent::getPropulsao();
    }

    public function setPotenciaMotor($potenciaMotor)
    {
        $this->__load();
        return parent::setPotenciaMotor($potenciaMotor);
    }

    public function getPotenciaMotor()
    {
        $this->__load();
        return parent::getPotenciaMotor();
    }

    public function setTripulacao($tripulacao)
    {
        $this->__load();
        return parent::setTripulacao($tripulacao);
    }

    public function getTripulacao()
    {
        $this->__load();
        return parent::getTripulacao();
    }

    public function setMunicipio(\Municipio $municipio)
    {
        $this->__load();
        return parent::setMunicipio($municipio);
    }

    public function getMunicipio()
    {
        $this->__load();
        return parent::getMunicipio();
    }

    public function getIdEmbarcacao()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idEmbarcacao"];
        }
        $this->__load();
        return parent::getIdEmbarcacao();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nome', 'autorizacaoPesca', 'regMarinha', 'regMpa', 'comprimBarco', 'arqueacaoBruta', 'anoFabricacao', 'matCasco', 'propulsao', 'potenciaMotor', 'tripulacao', 'idEmbarcacao', 'municipio');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}