<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CadAves extends \CadAves implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNomeComumBr($nomeComumBr)
    {
        $this->__load();
        return parent::setNomeComumBr($nomeComumBr);
    }

    public function getNomeComumBr()
    {
        $this->__load();
        return parent::getNomeComumBr();
    }

    public function setNomeCientifico($nomeCientifico)
    {
        $this->__load();
        return parent::setNomeCientifico($nomeCientifico);
    }

    public function getNomeCientifico()
    {
        $this->__load();
        return parent::getNomeCientifico();
    }

    public function setNomeComumEn($nomeComumEn)
    {
        $this->__load();
        return parent::setNomeComumEn($nomeComumEn);
    }

    public function getNomeComumEn()
    {
        $this->__load();
        return parent::getNomeComumEn();
    }

    public function getIdAves()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idAves"];
        }
        $this->__load();
        return parent::getIdAves();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nomeComumBr', 'nomeCientifico', 'nomeComumEn', 'idAves');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}