<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DadosAbioticos extends \DadosAbioticos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLance($lance)
    {
        $this->__load();
        return parent::setLance($lance);
    }

    public function getLance()
    {
        $this->__load();
        return parent::getLance();
    }

    public function setAnzois($anzois)
    {
        $this->__load();
        return parent::setAnzois($anzois);
    }

    public function getAnzois()
    {
        $this->__load();
        return parent::getAnzois();
    }

    public function setRegPeso($regPeso)
    {
        $this->__load();
        return parent::setRegPeso($regPeso);
    }

    public function getRegPeso()
    {
        $this->__load();
        return parent::getRegPeso();
    }

    public function setToriline($toriline)
    {
        $this->__load();
        return parent::setToriline($toriline);
    }

    public function getToriline()
    {
        $this->__load();
        return parent::getToriline();
    }

    public function setIscaTingida($iscaTingida)
    {
        $this->__load();
        return parent::setIscaTingida($iscaTingida);
    }

    public function getIscaTingida()
    {
        $this->__load();
        return parent::getIscaTingida();
    }

    public function setCruzeiro(\Cruzeiro $cruzeiro = NULL)
    {
        $this->__load();
        return parent::setCruzeiro($cruzeiro);
    }

    public function getCruzeiro()
    {
        $this->__load();
        return parent::getCruzeiro();
    }

    public function setDadosAbioticosLancamento(\DadosAbioticosLancamento $dadosAbioticosLancamento = NULL)
    {
        $this->__load();
        return parent::setDadosAbioticosLancamento($dadosAbioticosLancamento);
    }

    public function getDadosAbioticosLancamento()
    {
        $this->__load();
        return parent::getDadosAbioticosLancamento();
    }

    public function setDadosAbioticosRecolhimento(\DadosAbioticosRecolhimento $dadosAbioticosRecolhimento = NULL)
    {
        $this->__load();
        return parent::setDadosAbioticosRecolhimento($dadosAbioticosRecolhimento);
    }

    public function addIscas(\CadIsca $isca)
    {
        $this->__load();
        return parent::addIscas($isca);
    }

    public function removeIscas(\CadIsca $isca)
    {
        $this->__load();
        return parent::removeIscas($isca);
    }

    public function getIscas()
    {
        $this->__load();
        return parent::getIscas();
    }

    public function getDadosAbioticosRecolhimento()
    {
        $this->__load();
        return parent::getDadosAbioticosRecolhimento();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function __toJson()
    {
        $this->__load();
        return parent::__toJson();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'lance', 'anzois', 'regPeso', 'toriline', 'iscaTingida', 'iscas', 'cruzeiro', 'dadosAbioticosLancamento', 'dadosAbioticosRecolhimento');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}