<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DadosAbioticosRecolhimento extends \DadosAbioticosRecolhimento implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCoordenadaInicio($coordenadaInicio)
    {
        $this->__load();
        return parent::setCoordenadaInicio($coordenadaInicio);
    }

    public function getCoordenadaInicio()
    {
        $this->__load();
        return parent::getCoordenadaInicio();
    }

    public function setCoordenadaFim($coordenadaFim)
    {
        $this->__load();
        return parent::setCoordenadaFim($coordenadaFim);
    }

    public function getCoordenadaFim()
    {
        $this->__load();
        return parent::getCoordenadaFim();
    }

    public function setDataInicio($dataInicio)
    {
        $this->__load();
        return parent::setDataInicio($dataInicio);
    }

    public function getDataInicio()
    {
        $this->__load();
        return parent::getDataInicio();
    }

    public function setDataFim($dataFim)
    {
        $this->__load();
        return parent::setDataFim($dataFim);
    }

    public function getDataFim()
    {
        $this->__load();
        return parent::getDataFim();
    }

    public function setProfundidadeInicio($profundidadeInicio)
    {
        $this->__load();
        return parent::setProfundidadeInicio($profundidadeInicio);
    }

    public function getProfundidadeInicio()
    {
        $this->__load();
        return parent::getProfundidadeInicio();
    }

    public function setProfundidadeFim($profundidadeFim)
    {
        $this->__load();
        return parent::setProfundidadeFim($profundidadeFim);
    }

    public function getProfundidadeFim()
    {
        $this->__load();
        return parent::getProfundidadeFim();
    }

    public function setRumoInicio($rumoInicio)
    {
        $this->__load();
        return parent::setRumoInicio($rumoInicio);
    }

    public function getRumoInicio()
    {
        $this->__load();
        return parent::getRumoInicio();
    }

    public function setRumoFim($rumoFim)
    {
        $this->__load();
        return parent::setRumoFim($rumoFim);
    }

    public function getRumoFim()
    {
        $this->__load();
        return parent::getRumoFim();
    }

    public function setDirecaoVentoInicio($direcaoVentoInicio)
    {
        $this->__load();
        return parent::setDirecaoVentoInicio($direcaoVentoInicio);
    }

    public function getDirecaoVentoInicio()
    {
        $this->__load();
        return parent::getDirecaoVentoInicio();
    }

    public function setDirecaoVentoFim($direcaoVentoFim)
    {
        $this->__load();
        return parent::setDirecaoVentoFim($direcaoVentoFim);
    }

    public function getDirecaoVentoFim()
    {
        $this->__load();
        return parent::getDirecaoVentoFim();
    }

    public function setVelocidadeVentoInicio($velocidadeVentoInicio)
    {
        $this->__load();
        return parent::setVelocidadeVentoInicio($velocidadeVentoInicio);
    }

    public function getVelocidadeVentoInicio()
    {
        $this->__load();
        return parent::getVelocidadeVentoInicio();
    }

    public function setVelocidadeVentoFim($velocidadeVentoFim)
    {
        $this->__load();
        return parent::setVelocidadeVentoFim($velocidadeVentoFim);
    }

    public function getVelocidadeVentoFim()
    {
        $this->__load();
        return parent::getVelocidadeVentoFim();
    }

    public function setCategoriaMarInicio($categoriaMarInicio)
    {
        $this->__load();
        return parent::setCategoriaMarInicio($categoriaMarInicio);
    }

    public function getCategoriaMarInicio()
    {
        $this->__load();
        return parent::getCategoriaMarInicio();
    }

    public function setCategoriaMarFim($categoriaMarFim)
    {
        $this->__load();
        return parent::setCategoriaMarFim($categoriaMarFim);
    }

    public function getCategoriaMarFim()
    {
        $this->__load();
        return parent::getCategoriaMarFim();
    }

    public function setTemperaturaArInicio($temperaturaArInicio)
    {
        $this->__load();
        return parent::setTemperaturaArInicio($temperaturaArInicio);
    }

    public function getTemperaturaArInicio()
    {
        $this->__load();
        return parent::getTemperaturaArInicio();
    }

    public function setTemperaturaArFim($temperaturaArFim)
    {
        $this->__load();
        return parent::setTemperaturaArFim($temperaturaArFim);
    }

    public function getTemperaturaArFim()
    {
        $this->__load();
        return parent::getTemperaturaArFim();
    }

    public function setTemperaturaSupMarInicio($temperaturaSupMarInicio)
    {
        $this->__load();
        return parent::setTemperaturaSupMarInicio($temperaturaSupMarInicio);
    }

    public function getTemperaturaSupMarInicio()
    {
        $this->__load();
        return parent::getTemperaturaSupMarInicio();
    }

    public function setTemperaturaSupMarFim($temperaturaSupMarFim)
    {
        $this->__load();
        return parent::setTemperaturaSupMarFim($temperaturaSupMarFim);
    }

    public function getTemperaturaSupMarFim()
    {
        $this->__load();
        return parent::getTemperaturaSupMarFim();
    }

    public function setCoberturaCeuInicio($coberturaCeuInicio)
    {
        $this->__load();
        return parent::setCoberturaCeuInicio($coberturaCeuInicio);
    }

    public function getCoberturaCeuInicio()
    {
        $this->__load();
        return parent::getCoberturaCeuInicio();
    }

    public function setCoberturaCeuFim($coberturaCeuFim)
    {
        $this->__load();
        return parent::setCoberturaCeuFim($coberturaCeuFim);
    }

    public function getCoberturaCeuFim()
    {
        $this->__load();
        return parent::getCoberturaCeuFim();
    }

    public function setPressaoAtmosfericaInicio($pressaoAtmosfericaInicio)
    {
        $this->__load();
        return parent::setPressaoAtmosfericaInicio($pressaoAtmosfericaInicio);
    }

    public function getPressaoAtmosfericaInicio()
    {
        $this->__load();
        return parent::getPressaoAtmosfericaInicio();
    }

    public function setPressaoAtmosfericaFim($pressaoAtmosfericaFim)
    {
        $this->__load();
        return parent::setPressaoAtmosfericaFim($pressaoAtmosfericaFim);
    }

    public function getPressaoAtmosfericaFim()
    {
        $this->__load();
        return parent::getPressaoAtmosfericaFim();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'coordenadaInicio', 'coordenadaFim', 'dataInicio', 'dataFim', 'profundidadeInicio', 'profundidadeFim', 'rumoInicio', 'rumoFim', 'direcaoVentoInicio', 'direcaoVentoFim', 'velocidadeVentoInicio', 'velocidadeVentoFim', 'categoriaMarInicio', 'categoriaMarFim', 'temperaturaArInicio', 'temperaturaArFim', 'temperaturaSupMarInicio', 'temperaturaSupMarFim', 'coberturaCeuInicio', 'coberturaCeuFim', 'pressaoAtmosfericaInicio', 'pressaoAtmosfericaFim');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}